// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA9DnOszGPhMnvfYUHWF4BIA4xAr29k3M',
    appId: '1:224906061074:web:cb3738e8fd4fc2ad53ffcb',
    messagingSenderId: '224906061074',
    projectId: 'test-database-d1555',
    authDomain: 'test-database-d1555.firebaseapp.com',
    storageBucket: 'test-database-d1555.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA9bcQg7JMOR5mH3nZlqt0t9o_hBpcY48',
    appId: '1:224906061074:android:0f485ba35a9b8bbe53ffcb',
    messagingSenderId: '224906061074',
    projectId: 'test-database-d1555',
    storageBucket: 'test-database-d1555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYCNfkvT7V5T2HPab_SvNTmEJxLDnfB9c',
    appId: '1:224906061074:ios:6ac1f6f6c52f0e1553ffcb',
    messagingSenderId: '224906061074',
    projectId: 'test-database-d1555',
    storageBucket: 'test-database-d1555.firebasestorage.app',
    iosBundleId: 'com.example.aoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYCNfkvT7V5T2HPab_SvNTmEJxLDnfB9c',
    appId: '1:224906061074:ios:6ac1f6f6c52f0e1553ffcb',
    messagingSenderId: '224906061074',
    projectId: 'test-database-d1555',
    storageBucket: 'test-database-d1555.firebasestorage.app',
    iosBundleId: 'com.example.aoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA9DnOszGPhMnvfYUHWF4BIA4xAr29k3M',
    appId: '1:224906061074:web:da9024399841c93d53ffcb',
    messagingSenderId: '224906061074',
    projectId: 'test-database-d1555',
    authDomain: 'test-database-d1555.firebaseapp.com',
    storageBucket: 'test-database-d1555.firebasestorage.app',
  );
}
