// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlrEoXO3LQypfOTH0Ifx0wg7RVEE5rD8',
    appId: '1:567554381312:web:7fc4b5f386d3b0e7ad2ae5',
    messagingSenderId: '567554381312',
    projectId: 'condor-application-14288',
    authDomain: 'condor-application-14288.firebaseapp.com',
    storageBucket: 'condor-application-14288.firebasestorage.app',
    measurementId: 'G-HYW4J7DW7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJglmG5U3Z8p8Sn5cdr2B1DViJt4XKhTM',
    appId: '1:567554381312:android:d8f662db2fe33e6aad2ae5',
    messagingSenderId: '567554381312',
    projectId: 'condor-application-14288',
    storageBucket: 'condor-application-14288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtO6bY1hDNdrcWlGp2CL7LisaN93xmBYM',
    appId: '1:567554381312:ios:53727ad963d3ba2bad2ae5',
    messagingSenderId: '567554381312',
    projectId: 'condor-application-14288',
    storageBucket: 'condor-application-14288.firebasestorage.app',
    iosClientId: '567554381312-ah3j98id4mushkvi66k6va4hl18u97ka.apps.googleusercontent.com',
    iosBundleId: 'com.example.aoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtO6bY1hDNdrcWlGp2CL7LisaN93xmBYM',
    appId: '1:567554381312:ios:53727ad963d3ba2bad2ae5',
    messagingSenderId: '567554381312',
    projectId: 'condor-application-14288',
    storageBucket: 'condor-application-14288.firebasestorage.app',
    iosClientId: '567554381312-ah3j98id4mushkvi66k6va4hl18u97ka.apps.googleusercontent.com',
    iosBundleId: 'com.example.aoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHlrEoXO3LQypfOTH0Ifx0wg7RVEE5rD8',
    appId: '1:567554381312:web:5437cc5f78d0977dad2ae5',
    messagingSenderId: '567554381312',
    projectId: 'condor-application-14288',
    authDomain: 'condor-application-14288.firebaseapp.com',
    storageBucket: 'condor-application-14288.firebasestorage.app',
    measurementId: 'G-RV7Q41RS72',
  );
}
